# Generated by Django 5.2.7 on 2025-11-10 02:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeatureSelectionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("RUNNING", "Ejecutando"),
                            ("COMPLETE", "Completo"),
                            ("FAILED", "Falló"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("model_params", models.JSONField(default=dict)),
                ("top_n_features", models.IntegerField(default=10)),
                ("results", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
