# Generated by Django 5.2.7 on 2025-12-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureselectionjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("RF", "Random Forest (Selección de Características)"),
                    ("KM", "Clustering (K-Means)"),
                ],
                default="RF",
                max_length=2,
            ),
        ),
    ]
