# Generated by Django 5.2.7 on 2025-12-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_featureselectionjob_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureselectionjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("RF", "Random Forest (Selección de Características)"),
                    ("KM", "Clustering (K-Means)"),
                    ("DB", "Clustering (DBSCAN)"),
                ],
                default="RF",
                max_length=10,
            ),
        ),
    ]
